/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Login;

/**
 *
 * @author MYPCDESU
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    private Connection conn;
    private PreparedStatement stmt;
    private ResultSet rs;
    public AdminForm() {
        initComponents();
        try {
			conn = DBUtil.getConnection();
		} catch (Exception e) {
			e.printStackTrace();
		}
		showAdmin();
		showGiaovien();
		showGiaovu();
        this.setTitle("Administrator");
        this.setLocationRelativeTo(null);
        this.setBackground(Color.WHITE);
    }
    public AdminForm(Login login) {
        initComponents();
        try {
			conn = DBUtil.getConnection();
		} catch (Exception e) {
			e.printStackTrace();
		}
		showAdmin();
		showGiaovien();
		showGiaovu();
        this.setTitle("Administrator");
        this.setLocationRelativeTo(null);
        this.setBackground(Color.WHITE);
        user.setText(login.getUser());
        JOptionPane.showMessageDialog(null, login.getHello());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        user = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        txtIDAD = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        txtUserAD = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        txtPassAD = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnAddAdmin = new javax.swing.JButton();
        btnEditAdmin = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        btnResetAdmin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGiaovu = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        txtIDGiaovu = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        txtUserGiaovu = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        txtPassGiaovu = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnAddGiaovu = new javax.swing.JButton();
        btnEditGiaovu = new javax.swing.JButton();
        btnDelGiaovu = new javax.swing.JButton();
        btnResetGiaovu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableGiaovien = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        label9 = new java.awt.Label();
        txtIDGV = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        txtUserGV = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        txtPassGV = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        btnAddGV = new javax.swing.JButton();
        btnEditGV = new javax.swing.JButton();
        btnDelGV = new javax.swing.JButton();
        btnResetGV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 255));
        label1.setText("Xin chào ");

        user.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        user.setText("label2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cookies-icon (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableAdmin.setPreferredSize(new java.awt.Dimension(250, 72));
        tableAdmin.setRowHeight(18);
        tableAdmin.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableAdmin);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        label3.setText("ID Admin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel5.add(label3, gridBagConstraints);

        txtIDAD.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel5.add(txtIDAD, gridBagConstraints);

        label4.setText("User name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel5.add(label4, gridBagConstraints);

        txtUserAD.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel5.add(txtUserAD, gridBagConstraints);

        label5.setText("Password: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel5.add(label5, gridBagConstraints);

        txtPassAD.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel5.add(txtPassAD, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnAddAdmin.setText("Thêm");
        btnAddAdmin.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel7.add(btnAddAdmin, gridBagConstraints);

        btnEditAdmin.setText("Sửa");
        btnEditAdmin.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnEditAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel7.add(btnEditAdmin, gridBagConstraints);

        btnDeleteAdmin.setText("Xóa");
        btnDeleteAdmin.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel7.add(btnDeleteAdmin, gridBagConstraints);

        btnResetAdmin.setText("Reset");
        btnResetAdmin.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnResetAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel7.add(btnResetAdmin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel5.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel6.add(jPanel5, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tài khoản Admin", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        tableGiaovu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableGiaovu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableGiaovu.setPreferredSize(new java.awt.Dimension(250, 72));
        tableGiaovu.setRowHeight(18);
        tableGiaovu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tableGiaovu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jScrollPane2, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        label6.setText("ID Giáo vụ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel9.add(label6, gridBagConstraints);

        txtIDGiaovu.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel9.add(txtIDGiaovu, gridBagConstraints);

        label7.setText("User name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel9.add(label7, gridBagConstraints);

        txtUserGiaovu.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel9.add(txtUserGiaovu, gridBagConstraints);

        label8.setText("Password: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel9.add(label8, gridBagConstraints);

        txtPassGiaovu.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel9.add(txtPassGiaovu, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        btnAddGiaovu.setText("Thêm");
        btnAddGiaovu.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnAddGiaovu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGiaovuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel10.add(btnAddGiaovu, gridBagConstraints);

        btnEditGiaovu.setText("Sửa");
        btnEditGiaovu.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnEditGiaovu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGiaovuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel10.add(btnEditGiaovu, gridBagConstraints);

        btnDelGiaovu.setText("Xóa");
        btnDelGiaovu.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnDelGiaovu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelGiaovuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel10.add(btnDelGiaovu, gridBagConstraints);

        btnResetGiaovu.setText("Reset");
        btnResetGiaovu.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnResetGiaovu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetGiaovuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel10.add(btnResetGiaovu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jPanel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel8.add(jPanel9, gridBagConstraints);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tài khoản Giáo vụ", jPanel3);

        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        tableGiaovien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableGiaovien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableGiaovien.setPreferredSize(new java.awt.Dimension(250, 72));
        tableGiaovien.setRowHeight(18);
        tableGiaovien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tableGiaovien);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel11.add(jScrollPane3, gridBagConstraints);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        label9.setText("ID Giáo viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel12.add(label9, gridBagConstraints);

        txtIDGV.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel12.add(txtIDGV, gridBagConstraints);

        label10.setText("User name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel12.add(label10, gridBagConstraints);

        txtUserGV.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel12.add(txtUserGV, gridBagConstraints);

        label11.setText("Password: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel12.add(label11, gridBagConstraints);

        txtPassGV.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        jPanel12.add(txtPassGV, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        btnAddGV.setText("Thêm");
        btnAddGV.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnAddGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel13.add(btnAddGV, gridBagConstraints);

        btnEditGV.setText("Sửa");
        btnEditGV.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnEditGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel13.add(btnEditGV, gridBagConstraints);

        btnDelGV.setText("Xóa");
        btnDelGV.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnDelGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelGVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel13.add(btnDelGV, gridBagConstraints);

        btnResetGV.setText("Reset");
        btnResetGV.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnResetGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetGVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel13.add(btnResetGV, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel12.add(jPanel13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel11.add(jPanel12, gridBagConstraints);

        jPanel4.add(jPanel11, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tài khoản Giáo viên", jPanel4);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(172, 172, 172))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO project.admin (idad, user, pass) VALUES (?, ?, ?)";
				try {
					if(txtIDAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "ID admin không được để trống !");
					}else if(txtUserAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "Username không được để trống !");
					}else if(txtPassAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "Password không được để trống !");
					}else{
					stmt = conn.prepareStatement(sql);
					stmt.setString(1, txtIDAD.getText());
					stmt.setString(2, txtUserAD.getText());
					stmt.setString(3, txtPassAD.getText());
					stmt.executeUpdate();
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, "ID đã tồn tại !" );
				}
				showAdmin();
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnEditAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAdminActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE project.admin SET user=?, pass=? WHERE idad=?";
				try {
					if(txtIDAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "ID admin không được để trống !");
					}else if(txtUserAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "Username không được để trống !");
					}else if(txtPassAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "Password không được để trống !");
					}else{
					stmt = conn.prepareStatement(sql);
					stmt.setString(1, txtIDAD.getText());
					stmt.setString(2, txtUserAD.getText());
					stmt.setString(3, txtPassAD.getText());
					stmt.executeUpdate();
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, "ID đã tồn tại !");
				}
				showAdmin();
    }//GEN-LAST:event_btnEditAdminActionPerformed

    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM project.admin WHERE idad=?";
        try {
					stmt = conn.prepareStatement(sql);
					stmt.setString(1, txtIDAD.getText());
					int reponse = JOptionPane.showConfirmDialog(this,
							"Bạn có chắc chắn admin " + txtUserAD.getText() + " không?", "Delete person",
							JOptionPane.YES_NO_OPTION);
					String message = "?";
					switch (reponse) {
					case JOptionPane.YES_OPTION:
						message = "Xóa admin " + txtUserAD.getText() + " thành công!";
						stmt.executeUpdate();
						break;
					case JOptionPane.NO_OPTION:
						message = "Không xóa admin " + txtUserAD.getText();
						break;
					}
					JOptionPane.showMessageDialog(this, message);
				} catch (Exception e2) {
					e2.printStackTrace();
				}
				showAdmin();
    }//GEN-LAST:event_btnDeleteAdminActionPerformed

    private void btnResetAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAdminActionPerformed
        // TODO add your handling code here:
        txtIDAD.setText("");
        txtUserAD.setText("");
        txtPassAD.setText("");
    }//GEN-LAST:event_btnResetAdminActionPerformed

    private void btnAddGiaovuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGiaovuActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO project.giaovu (idgvu, user, pass) VALUES (?, ?, ?)";
				try {
					if(txtIDAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "ID giáo vụ không được để trống !");
					}else if(txtUserAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "Username không được để trống !");
					}else if(txtPassAD.getText().length()==0){
						JOptionPane.showMessageDialog(null, "Password không được để trống !");
					}else{
					stmt = conn.prepareStatement(sql);
					stmt.setString(1, txtIDAD.getText());
					stmt.setString(2, txtUserAD.getText());
					stmt.setString(3, txtPassAD.getText());
					stmt.executeUpdate();
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, "ID đã tồn tại !" );
				}
				showAdmin();
    }//GEN-LAST:event_btnAddGiaovuActionPerformed

    private void btnEditGiaovuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGiaovuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditGiaovuActionPerformed

    private void btnDelGiaovuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelGiaovuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelGiaovuActionPerformed

    private void btnResetGiaovuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetGiaovuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetGiaovuActionPerformed

    private void btnAddGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGVActionPerformed

    private void btnEditGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditGVActionPerformed

    private void btnDelGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelGVActionPerformed

    private void btnResetGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetGVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }
    
    public void showAdmin() {
		// Name Column table
		Vector cols = new Vector();
		cols.addElement("ID Admin");
		cols.addElement("Username");
		cols.addElement("Password");

		// Data table
		Vector data = new Vector();
		String sql = "SELECT * FROM project.admin";
		try {
			stmt = conn.prepareStatement(sql);
			rs = stmt.executeQuery();
			int row = 0;
			while (rs.next()) {
				Vector admin = new Vector();
				admin.addElement(rs.getString("idad"));
				admin.addElement(rs.getString("user"));
				admin.addElement(rs.getString("pass"));

				data.add(admin);
			}

		} catch (Exception e) {
			// TODO: handle exception
		}
		tableAdmin.setModel(new DefaultTableModel(data, cols));
	}

	public void showGiaovien() {
		// Name Column table
		Vector cols = new Vector();
		cols.addElement("ID giáo viên");
		cols.addElement("Username");
		cols.addElement("Password");

		// Data table
		Vector data = new Vector();
		String sql = "SELECT * FROM project.giaovien";
		try {
			stmt = conn.prepareStatement(sql);
			rs = stmt.executeQuery();
			int row = 0;
			while (rs.next()) {
				Vector giaovien = new Vector();
				giaovien.addElement(rs.getString("idgv"));
				giaovien.addElement(rs.getString("hoten"));
				giaovien.addElement(rs.getString("pass"));

				data.add(giaovien);
			}

		} catch (Exception e) {
			// TODO: handle exception
		}
		tableGiaovien.setModel(new DefaultTableModel(data, cols));
	}

	public void showGiaovu() {
		// Name Column table
		Vector cols = new Vector();
		cols.addElement("ID giáo vụ");
		cols.addElement("Username");
		cols.addElement("Password");

		// Data table
		Vector data = new Vector();
		String sql = "SELECT * FROM project.giaovu";
		try {
			stmt = conn.prepareStatement(sql);
			rs = stmt.executeQuery();
			int row = 0;
			while (rs.next()) {
				Vector admin = new Vector();
				admin.addElement(rs.getString("idgvu"));
				admin.addElement(rs.getString("user"));
				admin.addElement(rs.getString("pass"));

				data.add(admin);
			}

		} catch (Exception e) {
			// TODO: handle exception
		}
		tableGiaovu.setModel(new DefaultTableModel(data, cols));
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddGV;
    private javax.swing.JButton btnAddGiaovu;
    private javax.swing.JButton btnDelGV;
    private javax.swing.JButton btnDelGiaovu;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnEditAdmin;
    private javax.swing.JButton btnEditGV;
    private javax.swing.JButton btnEditGiaovu;
    private javax.swing.JButton btnResetAdmin;
    private javax.swing.JButton btnResetGV;
    private javax.swing.JButton btnResetGiaovu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTable tableAdmin;
    private javax.swing.JTable tableGiaovien;
    private javax.swing.JTable tableGiaovu;
    private javax.swing.JTextField txtIDAD;
    private javax.swing.JTextField txtIDGV;
    private javax.swing.JTextField txtIDGiaovu;
    private javax.swing.JTextField txtPassAD;
    private javax.swing.JTextField txtPassGV;
    private javax.swing.JTextField txtPassGiaovu;
    private javax.swing.JTextField txtUserAD;
    private javax.swing.JTextField txtUserGV;
    private javax.swing.JTextField txtUserGiaovu;
    private java.awt.Label user;
    // End of variables declaration//GEN-END:variables
}
